/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BookTestSubmission = IDL.Record({
  'name' : IDL.Text,
  'testType' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllBookTestSubmissions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, BookTestSubmission))],
      ['query'],
    ),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ContactSubmission))],
      ['query'],
    ),
  'submitBookTest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BookTestSubmission = IDL.Record({
    'name' : IDL.Text,
    'testType' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllBookTestSubmissions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, BookTestSubmission))],
        ['query'],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ContactSubmission))],
        ['query'],
      ),
    'submitBookTest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };